version: 2

project_name: fwdlio

before:
  hooks:
    - go mod tidy
    - go run github.com/a-h/templ/cmd/templ@latest generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

nfpms:
  -
    id: fwdlio
    package_name: fwdlio
    formats:
      - apk
    contents:
      - src: ./public/**/*
        dst: /usr/share/fwdlio/public
    
    maintainer: "Patresi <patresi@example.com>"
    description: "Simple Go WebUI"
    license: "MIT"
    
archives:
  - format: tar.gz
    # this name template makes the archive name compatible with the default
    # goreleaser name template
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
